--get all firewall resource list
SELECT T1.RES_NAME,
       T1.RES_DESC,
       T1.RES_IP,
       T1.RES_PAUSED,
       T1.CITY_CODE,
       T1.COMPANY_CODE,
       T1.TYPE_CODE,
       T2.COMPANY_NAME,
       T3.TYPE_NAME,
       T4.CITY_NAME
  FROM (SELECT ID,
               R.RES_NAME,
               R.RES_DESC,
               R.RES_IP,
               R.RES_PAUSED,
               R.CITY_CODE,
               R.COMPANY_CODE,
               R.TYPE_CODE
          FROM SYS_RES_OBJ R
         WHERE R.CITY_CODE IS NOT NULL
           AND R.CLASS_ID = 1) T1
  LEFT JOIN (SELECT C.COMPANY_NAME, C.COMPANY_CODE
               FROM SYS_DEV_COMPANY C
              WHERE C.COMPANY_CODE IS NOT NULL) T2
    ON T1.COMPANY_CODE = T2.COMPANY_CODE
  LEFT JOIN (SELECT T.TYPE_NAME, T.TYPE_CODE
               FROM SYS_DEV_TYPE T
              WHERE T.TYPE_CODE IS NOT NULL) T3
    ON T1.TYPE_CODE = T3.TYPE_CODE
  LEFT JOIN (SELECT SC.CITY_CODE, SC.CITY_NAME
               FROM SYS_CITY SC
              WHERE SC.CITY_CODE IS NOT NULL) T4
    ON T4.CITY_CODE = T1.CITY_CODE;
--GET SON CITY BY CITY CODE
SELECT T.ID, T.CITY_NAME, T.CITY_CODE, T.CITY_LEVEL, T.PARENT_CODE
  FROM SYS_CITY T
 WHERE T.CITY_CODE IS NOT NULL
   AND T.PARENT_CODE = '17000';
